### ISSUE TITLE
Problem with finding Teensy

### ISSUE THREAD

**Issue by GameScrub** [luni64/TeensySharp#1]
Hello I have a Teensy 3.1 and I have been trying to use this wrapper to keep track of the teensy board.  I noticed that it only recognizes it immediately after I upload some code with Arduino.  After that it never recognizes the board.  

I'm using the buttons teensy example and I upload to the board and it works fine.  But the c# wrapper doesn't seem to find the board.

Only when I upload the code and it finds it and loses it.

Teensy 989820 connected on Com1
Teensy 989820 removed

**Comment by luni64** [comment]
Are you sure the code you upload to the board has USB Serial activated? Otherwise it will not show up on the bus as serial device.

**Comment by GameScrub** [comment]
Here is the sketch I'm using from Arduino.
[Buttons.txt](https://github.com/luni64/TeensySharp/files/34051/Buttons.txt)

The usb types available are 
1. serial
2. keyboard + mouse + joystick
3. serial + keyboard + mouse + joystick

I picked number 2 and 3.  Does it have to be 1 for the code to work?

**Comment by luni64** [comment]
TeensySharp currently detects Teensies in serial mode or in HID mode  (bootloader mode after pressing the button) only.  Can you do a simple test with serial mode (1) to check if everything works as expected?

Drop me a note if you need to detect teensies in mode 2) or 3). I can have a look if it is possible to find them in these modes.
