### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by atestani** [luni64/TeensySharp#2]
First, let me say that TeensySharp is an impressive piece of work and extremely useful.  Thanks for sharing it!

My application is programming "custom" Teensy based products in production.  Having purchased a quantity of MINI54 bootloader devices from PJRC,  I am programming "blank"  MK20DX256VLH7 devices.

The tester that the target MCU is in has two other "stock" Teensy 3.2 boards as controllers.  These show up as USB-Serial devices which I can use the Watcher class to detect vs the MCU to be programmed (which shows up with a serial number all 0xFF).

I have two questions:

1) Is there any way "programmatically" restart the HalfKay loader once an MK20DX256VLH7 has been programmed, i.e. to effectively press the programming button?  There may be times when an already programmed MCU has to be reprogrammed and once it is programmed it shows up as a USB-Serial device.

2) How do I use Watcher.ConnectedDevices.FirstOrDefault() to set the "default" serial number of the device I want to program?  There isn't a requirement for this, at this point, but I would like to better understand how to use Watcher.ConnectedDevices.

Thanks
Al

**Comment by luni64** [comment]
Al, 
glad to hear that TeensySharp is useful for you. 

Regarding your questions:
- For starting the bootloader you can use the `StartHalfKay(uint Serialnumber)` member of `SharpUploader`. Please have a look at the example code here: [https://github.com/luni64/TeensySharp/blob/master/02_FirmwareDownloadConsole/Program.cs](https://github.com/luni64/TeensySharp/blob/master/02_FirmwareDownloadConsole/Program.cs). Is this what you need? 
- I don't quite understand your second question. Do you want to program the serialnumber of the chip? This is not possible with TeensyWatcher. The stock teensies have serial numbers which are derived from a PJRC MAC and are set at PJRC. If you need something similar you need to program this number somehow. (I currently do not know how this is done). Or do you want to understand how to use 
`FirstOrDefault()`?

Lutz

**Comment by atestani** [comment]
Hi Lutz

Thanks for the quick response.

For the first question... that is exactly what I am looking for and will
proceed to use it.

On the second question is is the latter... how to use FirstorDefault().
Sorry for bother you with this being a "beginner" in C# (have been using
Delphi for years).  I subsequently realized that this is only a method of
the List class so I am now simply determining the index (idx) of the device
I am interested in and then doing this:

* USB_Device MCUtoPgm = Watcher.ConnectedDevices[idx];*

Thanks again for TeensySharp!

**Comment by luni64** [comment]
Working with the index is possible of course but it is quite old style :-) 
You can get a reference to the Device directly with FirstOrDefault(). E.g:
```
var MCUtoPgm = Watcher.ConnectedDevices.FirstOrDefault(d=>d.SerialNumber == 0xFFFF);
if(MCUtopGM != null)
{
  //  dosomenthing with the mcu
}
```
FirstOrDefault returns the first item in the list which matches any condition passed as argument. If it doesn't find an matching element it returns null. 
If you want to dig deeper into those things you should have a look at C# LINQ which is extremely useful if you deal with collections of data in C#

**Comment by atestani** [comment]
​Thanks.. I changed to using FirstorDefault.

I am not having success with
​*SharpUploader.StartHalfKay(MCUtoPgm.Serialnumber)
*effectively pushing the physical program button.

I can program the MCU once but then on the second pass of the program, it
is seen as a USBSerial device so even though I call StartHalfKay, it fails
with a result of 1 from *SharpUploader.Upload(FlashImage, Board,
MCUtoPgm.Serialnumber, reboot: true);  * If I run the program a third time,
 it is now recognized as a HalfKay device and it programs. It will toggle
like this forever.

I tried a Thread.Sleep(1000), before trying to Upload but no help there.
On every pass,  I get a SharpUploader.StartHalfKay result of the bootloader
is running.

If I change the Upload reboot parameter to false, it works every time but I
need for the MCU to start.  Of course, it works fine if I press the program
button between passes.  Overall, I can't make SharpUploader.StartHalfKay
replace physically pushing the button.  Any ideas on what I am doing wrong?

Thanks

**Comment by luni64** [comment]
That's strange. I'll have a look at it.

**Comment by luni64** [comment]
Al, 
I attached  a demo application which successively uploads two hex files. This works without problems as long as you wait between uploads until Windows updated the usb tree (couple of seconds)

Here the output of the application:

![image](https://user-images.githubusercontent.com/12611497/27270239-15275be0-54bd-11e7-8076-bd379cc9b7ed.png)

Can you please try if this works for you? (careful, it downloads to the first teensy found on the bus without asking...)

[UploadTest.zip](https://github.com/luni64/TeensySharp/files/1083847/UploadTest.zip)

**Comment by atestani** [comment]
Very strange.  This works fine with a stock Teensy 3.2 but not with my
system.  The only differences are:

   1. I have outboarded the MINI54 bootloader chip and circuitry to a small
   programmer board
   2. The rest of the Teensy 3.2 circuitry is on my own PCB and the same as
   on a Teensy board
   3. The MK20DX256LH7 on my board has no serial number burned into it so
   returns uint.MaxInt as a serial number


Below are two consecutive runs of UploadTest where you can see every other
time it works.  This is what I have been seeing in my own uploader.  I have
the delay set to 4 seconds but the length of the delay doesn't seem to
matter.  Also when I had another stock Teensy connected, it programmed both
my board and the other Teensy and then every other time my board would not
start the bootloader.

 I just noticed that the serial number being returned changes each pass!!
It doesn't work when it is truly MaxInt (4,294,967,295 (0xFFFFFFFF)), only
when it is 4,294,967,286 (0xFFFFFFF6). Another thing, is when it does work
I can hear one sound from Windows as the device is disconnected.  When it
doesn't work I hear it disconnect and then re-enumerate. These sounds
toggle just as the serial number does.

Any ideas?


[image: Inline image 1]
 [image: Inline image 2]

**Comment by luni64** [comment]
Images don't show.

Anyway, I think I understand what is happening. Stock Teensies report different serial numbers in serial mode and in bootloader mode. Bootloader SN is serial SN divided by 10. TeensySharp thus multiplies Bootlader SN's by 10 to get the correct value. In your case the board always reports  0xFFFFFFFF, TeensySharp multiplies by 10: 0xFFFFFFFF*d10 = 0xFFFFFFF6. That means after switching from serial to bootloader the board "vanishes" for TeensySharp  because it appears with a different SN.  

To get this going with your custom boards I see two possibilities:
1. Report the SN in the same way the stock Teensies do
2. Adopt TeensySharp for your use case

If you want me to do #2 for you please drop me a note at lutz.niggl@lunoptics.com.

**Comment by luni64** [comment]
Al, 
attached please find a new UploadTest, I suppressed the mulitplication if the SN is reported as 0xFFFFFFFF. This should fix your issue. 
[UploadTest2.zip](https://github.com/luni64/TeensySharp/files/1085748/UploadTest2.zip)

**Comment by atestani** [comment]
Works perfectly!!!

Thank you very much!

**Comment by luni64** [comment]
Very good, 
You're welcome

**Comment by luni64** [comment]
Just updated the main branch with the changes
