### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by TGlev** [luni64/TeensySharp#6]
Hi,

First of all I have to say that this is a very convenient little tool. Thank you for making it!
I'm currently developing a desktop application in Xamarin Forms, a cross platform app framework. They allow to share a codebase between multiple plaftorms. This way, I can make an app for windows and macos with almost 99% shared code. 

I've been looking to expand my application to MacOS, but I would need TeensySharp to support MacOS for that... I don't think it will currently work because of the way that the windows registries are queried.
`using (var searcher = new ManagementObjectSearcher("root\\CIMV2", "SELECT * FROM Win32_PnPEntity WHERE DeviceID LIKE " + vidStr))`

Is there a chance macos support could be added?

**Comment by luni64** [comment]
Glad you like it. Unfortunately I have no clue about MacOS, so I won't be of any help here. You might be able to just exchange the low level parts by MacOS specific code but I didn't develop it to be multiplatform, so there probably are a couple of places with OS specific code...
